# Generated by Django 4.2.14 on 2024-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('pageURL', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('tags', models.TextField()),
                ('webformatURL', models.URLField()),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
